### ISSUE TITLE
Make tests work

### ISSUE THREAD

**Issue by benjaoming** [learningequality/barbequeue#18]
This project should not go on with red test lights, it's not cool for a public project that's a core dependency.

**Comment by aronasorman** [comment]
I put in some effort last week to get travis tests working, but there are still some annoying timeouts here and there. https://travis-ci.org/learningequality/barbequeue/builds. I think it's related to Travis tests running on shared CPUs, and thus couldn't context switch fast enough.

I'll continue extending some of the waits in the tests.

**Comment by benjaoming** [comment]
We can live with a few occasional restarts, we'll probably find the cause sooner or later.

Great job!

Will add some coverage next up! :)
